---
title: "group3 script"
author: "Jessica Hunter"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

ˆ
```{r}
### Week 10a lab work ###
### Created by: Jocelyn Martinez, Ashlee Ochoa, Margarita Alfaro, Robert Dellinger ###
### Updated on: 2022-04-05 ###

# Load Libraries
library(tidyverse)
library(here)
#> here() starts at /private/var/folders/kz/08v85yjn2zn0cs16s9kvqjq00000gn/T/RtmpSYY0P9/reprex-110527756d0b0-ash-crane
library(reprex)
library(datapasta)
library(styler)

# Load data
chem_data <- read_csv(here("week_10/data","chemicaldata_maunalua.csv"))
#> Error: '/private/var/folders/kz/08v85yjn2zn0cs16s9kvqjq00000gn/T/RtmpSYY0P9/reprex-110527756d0b0-ash-crane/week_10/data/chemicaldata_maunalua.csv' does not exist.
view(chem_data)
#> Error in view(chem_data): object 'chem_data' not found

# Making a data tibble
chem <- tibble::tribble(
  ~Waypoint,        ~Zone,     ~Lat,      ~Long, ~Site,  ~Season, ~Tide_time,    ~Temp_in,   ~Salinity, ~Phosphate, ~Silicate,  ~NN,   ~pH,         ~TA, ~percent_sgd,
         1L, "Transition", 21.27531, -157.76181,   "W", "SPRING",  "Low_Day", 23.75505834,  27.7402879,       0.54,    157.93, 7.92, 7.909,  2161.48229,  20.40439276,
         2L, "Transition", 21.27523, -157.76265,   "W", "SPRING",  "Low_Day", 23.53255956,  30.6119226,       0.36,     92.59, 3.37, 7.965, 2145.827701,   11.9625323,
         3L, "Transition", 21.27504, -157.76328,   "W", "SPRING",  "Low_Day", 22.63449814, 28.37007862,        0.5,     143.6, 7.29, 8.023,  2272.39081,  18.55297158,
         4L, "Transition", 21.27449, -157.76402,   "W", "SPRING",  "Low_Day", 24.01982367, 32.82124424,       0.25,     42.32, 0.79, 7.995, 2219.583262,  5.467700258,
         5L,    "Diffuse", 21.27503,  -157.7617,   "W", "SPRING",  "Low_Day", 23.26102354, 29.12292683,        0.5,    126.47, 7.45, 8.005, 2151.825559,  16.33979328,
         6L,    "Diffuse", 21.27485, -157.76234,   "W", "SPRING",  "Low_Day", 24.00516582,  34.0201759,       0.13,     15.04, 0.46, 8.019,   2216.7581,  1.943152455,
         7L,    "Diffuse", 21.27463, -157.76318,   "W", "SPRING",  "Low_Day", 23.72550249, 32.20639623,       0.28,     56.31, 1.59, 8.003, 2220.335875,  7.275193798,
         8L,    "Diffuse", 21.27436, -157.76364,   "W", "SPRING",  "Low_Day", 24.08231046, 33.66594609,       0.15,      23.1, 0.34, 7.978, 2266.862576,  2.984496124,
         9L,    "Diffuse", 21.27456, -157.76126,   "W", "SPRING",  "Low_Day", 24.61700769, 32.66478542,       0.23,     45.88, 1.91, 7.972, 2189.458388,  5.927648579
  )

# Making a graph with chem tibble
chem %>% 
  ggplot() +
  geom_point(aes(x = Zone, y = Temp_in))
#> Error in layer(data = data, mapping = mapping, stat = stat, geom = GeomPoint, : object 'Zone' not found
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       macOS Big Sur 10.16
#>  system   x86_64, darwin17.0
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Los_Angeles
#>  date     2022-04-05
#>  pandoc   2.14.0.3 @ /Volumes/RStudio-2021.09.2-382/RStudio.app/Contents/MacOS/pandoc/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
#>  backports     1.4.1   2021-12-13 [1] CRAN (R 4.1.0)
#>  bit           4.0.4   2020-08-04 [1] CRAN (R 4.1.0)
#>  bit64         4.0.5   2020-08-30 [1] CRAN (R 4.1.0)
#>  broom         0.7.12  2022-01-28 [1] CRAN (R 4.1.2)
#>  cellranger    1.1.0   2016-07-27 [1] CRAN (R 4.1.0)
#>  cli           3.2.0   2022-02-14 [1] CRAN (R 4.1.2)
#>  colorspace    2.0-3   2022-02-21 [1] CRAN (R 4.1.2)
#>  crayon        1.5.0   2022-02-14 [1] CRAN (R 4.1.2)
#>  datapasta   * 3.1.0   2020-01-17 [1] CRAN (R 4.1.0)
#>  DBI           1.1.2   2021-12-20 [1] CRAN (R 4.1.0)
#>  dbplyr        2.1.1   2021-04-06 [1] CRAN (R 4.1.0)
#>  digest        0.6.29  2021-12-01 [1] CRAN (R 4.1.0)
#>  dplyr       * 1.0.8   2022-02-08 [1] CRAN (R 4.1.2)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)
#>  fansi         1.0.2   2022-01-14 [1] CRAN (R 4.1.2)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
#>  forcats     * 0.5.1   2021-01-27 [1] CRAN (R 4.1.0)
#>  fs            1.5.2   2021-12-08 [1] CRAN (R 4.1.0)
#>  generics      0.1.2   2022-01-31 [1] CRAN (R 4.1.2)
#>  ggplot2     * 3.3.5   2021-06-25 [1] CRAN (R 4.1.0)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.1.2)
#>  gtable        0.3.0   2019-03-25 [1] CRAN (R 4.1.0)
#>  haven         2.4.3   2021-08-04 [1] CRAN (R 4.1.0)
#>  here        * 1.0.1   2020-12-13 [1] CRAN (R 4.1.0)
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.1.0)
#>  hms           1.1.1   2021-09-26 [1] CRAN (R 4.1.0)
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.0)
#>  httr          1.4.2   2020-07-20 [1] CRAN (R 4.1.0)
#>  jsonlite      1.8.0   2022-02-22 [1] CRAN (R 4.1.2)
#>  knitr         1.37    2021-12-16 [1] CRAN (R 4.1.0)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.0)
#>  lubridate     1.8.0   2021-10-07 [1] CRAN (R 4.1.0)
#>  magrittr      2.0.2   2022-01-26 [1] CRAN (R 4.1.2)
#>  modelr        0.1.8   2020-05-19 [1] CRAN (R 4.1.0)
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
#>  pillar        1.7.0   2022-02-01 [1] CRAN (R 4.1.2)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
#>  purrr       * 0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
#>  R.cache       0.15.0  2021-04-30 [1] CRAN (R 4.1.0)
#>  R.methodsS3   1.8.1   2020-08-26 [1] CRAN (R 4.1.0)
#>  R.oo          1.24.0  2020-08-26 [1] CRAN (R 4.1.0)
#>  R.utils       2.11.0  2021-09-26 [1] CRAN (R 4.1.0)
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.0)
#>  Rcpp          1.0.8   2022-01-13 [1] CRAN (R 4.1.2)
#>  readr       * 2.1.2   2022-01-30 [1] CRAN (R 4.1.2)
#>  readxl        1.3.1   2019-03-13 [1] CRAN (R 4.1.0)
#>  reprex      * 2.0.1   2021-08-05 [1] CRAN (R 4.1.0)
#>  rlang         1.0.2   2022-03-04 [1] CRAN (R 4.1.2)
#>  rmarkdown     2.11    2021-09-14 [1] CRAN (R 4.1.0)
#>  rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
#>  rvest         1.0.2   2021-10-16 [1] CRAN (R 4.1.0)
#>  scales        1.1.1   2020-05-11 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.0)
#>  stringi       1.7.6   2021-11-29 [1] CRAN (R 4.1.0)
#>  stringr     * 1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
#>  styler      * 1.7.0   2022-03-13 [1] CRAN (R 4.1.2)
#>  tibble      * 3.1.6   2021-11-07 [1] CRAN (R 4.1.0)
#>  tidyr       * 1.2.0   2022-02-01 [1] CRAN (R 4.1.2)
#>  tidyselect    1.1.2   2022-02-21 [1] CRAN (R 4.1.2)
#>  tidyverse   * 1.3.1   2021-04-15 [1] CRAN (R 4.1.0)
#>  tzdb          0.2.0   2021-10-27 [1] CRAN (R 4.1.0)
#>  utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
#>  vroom         1.5.7   2021-11-30 [1] CRAN (R 4.1.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.1.2)
#>  xfun          0.29    2021-12-14 [1] CRAN (R 4.1.0)
#>  xml2          1.3.3   2021-11-30 [1] CRAN (R 4.1.0)
#>  yaml          2.2.2   2022-01-25 [1] CRAN (R 4.1.2)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
#> 
```
