---
title: "Master Scripts"
author: "Jessica Hunter"
date: "3/17/2022"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## gganimate


```{r}
library(patchwork)
library(ggrepel)
library(gganimate)
library(magick)
library(ggplot2)
library(here)
library(palmerpenguins)
```


```{r}
p1 <- penguins %>% 
    ggplot(aes(x = body_mass_g, 
             y = bill_length_mm, 
             color = species))+
  geom_point()
p1
```


```{r}
p2<-penguins %>%
  ggplot(aes(x = sex, 
             y = body_mass_g, 
             color = species))+
  geom_jitter(width = 0.2)
p2
```


```{r}
p1 + p2 +
  plot_layout(guides = 'collect')+
  plot_annotation(tag_levels = 'A')
```
```{r}
p1/p2 +
  plot_layout(guides = 'collect')+
  plot_annotation(tag_levels = 'A')
```



```{r}
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text() + # creates a text label
  geom_point(color = 'red')



```




```{r}
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text_repel() + # repel them
  geom_point(color = 'red')


```

```{r}


ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_label_repel() + # repel them 
  geom_point(color = 'red')
# label gives box and text gives no box

```
### label gives box and text gives no box

view(mtcars)

```{r}
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
    year, # what we are animating by
    transition_length = 2,
    state_length = 1
  ) +
  ease_aes("sine-in-out") + # or 'bounce-in-out'
  ggtitle('Year: {closest_state}') # no plus!!!
  anim_save(here("week_8","output8","mypengiungif.gif"))
           # animate(penguins, renderer = gifski_renderer()))
# state length is opause
# transition length is 
# curly bracket means take me out of quotes


```

### Magick 
```{r}
penguin<-image_read("https://pngimg.com/uploads/penguin/pinguin_PNG9.png")
penguin
```
### Save plot as picture

```{r}
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() 
  ggsave(here("week_8", "output8", "penguinplot.png"))
```

### make a composite plot

```{r}
penplot<-image_read(here("week_8","output8","penguinplot.png"))
out <- image_composite(penplot, penguin, offset = "+70+30")
out
```


## lubridate

```{r}

library(tidyverse)
library(lubridate)
library(here)
# make a character string
datetimes<-c("02/24/2021 22:22:20", 
             "02/25/2021 11:21:10", 
             "02/26/2021 8:01:52") 
# convert to datetimes
datetimes <- mdy_hms(datetimes) 
month(datetimes, label = TRUE, abbr = FALSE) #Spell it out 
day(datetimes) # extract day 
wday(datetimes, label = TRUE) # extract day of week

hour(datetimes)
minute(datetimes)
second(datetimes)
datetimes + hours(4) # this adds 4 hours
datetimes + days(2) # this adds 2 days
round_date(datetimes, "5 mins")
condata <- read_csv(here("week_5","data5", "CondData.csv"))
condata <- condata %>% 
  mutate(dateandtime = mdy_hms(depth))
glimpse(condata)

condata <- read_csv(here("week_5","data5", "CondData.csv")) %>% # read in the data
  mutate(dateandtime = mdy_hms(depth), # convert to datetime
         dateandtime = round_date(dateandtime, "10 seconds")) %>% 
  drop_na() %>%  # dropping missing data to no more na's
  select(!depth)  # to remove the depth,
view(condata)  

depdata <- read_csv(here("week_5", "data5", "DepthData.csv")) %>% 
  mutate(dateandtime = ymd_hms(date)) # have to list in the format it is in for program to find
view(depdata)

dep_con_data <- inner_join(depdata,condata) %>% 
  select(!date) %>% 
  # separate(col = dateandtime,
  #          into = c("date","time"),
  #          sep=" ",
  #          remove = FALSE) %>% # to keep the original column
  mutate(timebyminute = round_date(dateandtime, "1 minute")) %>%
  group_by(timebyminute) %>% # grouping variable
  summarise_at(vars(c("dateandtime","TempInSitu","Depth","SalinityInSitu_1pCal")), list(mean = mean))

dep_con_data %>% 
  ggplot(mapping = aes(x= dateandtime_mean,
             y = SalinityInSitu_1pCal_mean)) +
  geom_smooth()

```

## ggmaps
### Notes

when publishing have to have a compass and a scale bar



```{r}
library(ggmap)
library(tidyverse)
library(here)
#library(ggsn)

# register_google(key = "Write your API here", write = TRUE) ### use your own API
#IMPORTANT don't put your key to github!! I usually save mine in a text file and import it each time
# Setting write = TRUE will write the API key to your R environment so that you
```



```{r}
ChemData<-read_csv(here("Week_7","data7","chemicaldata_maunalua.csv"))
glimpse(ChemData)
```
